### ISSUE TITLE
Current implementation does not support Testerra 1.0-RC-34

### ISSUE THREAD

**Issue by martingrossmann** [telekom/testerra-selenoid-connector#3]
**Describe the bug**
The current version 1.0-RC-14 does not support the latest Testerra version. At runtime, the following error occurs:

`
An error occurred while instantiating class eu.tsystems.mms.testerra.demo.tests.TheInternetTest: eu/tsystems/mms/tic/testframework/webdrivermanager/DesktopWebDriverFactory
	at org.testng.internal.InstanceCreator.createInstanceUsingObjectFactory(InstanceCreator.java:123)
	at org.testng.internal.InstanceCreator.createInstance(InstanceCreator.java:79)
	at org.testng.internal.ClassImpl.getDefaultInstance(ClassImpl.java:109)
	at org.testng.internal.ClassImpl.getInstances(ClassImpl.java:167)
	at org.testng.TestClass.getInstances(TestClass.java:102)
	at org.testng.TestClass.initTestClassesAndInstances(TestClass.java:82)
	at org.testng.TestClass.init(TestClass.java:74)
	at org.testng.TestClass.<init>(TestClass.java:39)
	at org.testng.TestRunner.initMethods(TestRunner.java:457)
	at org.testng.TestRunner.init(TestRunner.java:336)
	at org.testng.TestRunner.init(TestRunner.java:289)
	at org.testng.TestRunner.<init>(TestRunner.java:180)
	at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:613)
	at org.testng.SuiteRunner.init(SuiteRunner.java:178)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:112)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1306)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1282)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1131)
	at org.testng.TestNG.runSuites(TestNG.java:1069)
	at org.testng.TestNG.run(TestNG.java:1037)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
Caused by: java.lang.NoClassDefFoundError: eu/tsystems/mms/tic/testframework/webdrivermanager/DesktopWebDriverFactory
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
	at java.base/java.lang.Class.getConstructor0(Class.java:3342)
	at java.base/java.lang.Class.getConstructor(Class.java:2151)
	at eu.tsystems.mms.tic.testframework.boot.Booter.lambda$initHooks$3(Booter.java:133)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at eu.tsystems.mms.tic.testframework.boot.Booter.initHooks(Booter.java:131)
	at eu.tsystems.mms.tic.testframework.boot.Booter.<clinit>(Booter.java:52)
	at eu.tsystems.mms.tic.testframework.testing.TesterraTest.<clinit>(TesterraTest.java:36)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.testng.internal.ObjectFactoryImpl.newInstance(ObjectFactoryImpl.java:23)
	at org.testng.internal.InstanceCreator.instantiateUsingDefaultConstructor(InstanceCreator.java:193)
	at org.testng.internal.InstanceCreator.createInstanceUsingObjectFactory(InstanceCreator.java:113)
	... 21 more
Caused by: java.lang.ClassNotFoundException: eu.tsystems.mms.tic.testframework.webdrivermanager.DesktopWebDriverFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 53 more
Exception in thread "Thread-1" java.lang.NoClassDefFoundError: Could not initialize class eu.tsystems.mms.tic.testframework.boot.Booter
	at eu.tsystems.mms.tic.testframework.report.TesterraListener.lambda$static$0(TesterraListener.java:155)
	at java.base/java.lang.Thread.run(Thread.java:834)
`

**To Reproduce**
Use in a Testerra project 
* Testerra 1.0-RC-34
* Selenoid connector 1.0-RC-14
* Run a test

**IntelliJ**
* IntelliJ is marking an issue at `VideoDesktopWebDriverFactory`, it cannot find class `DesktopWebDriverFactory`
* Bu the whole project is compiling successfully!

The Selenoid connector is working with 1.0-RC-33.

**Comment by martingrossmann** [comment]
Oh no... it seeems to be an IntelliJ issue when test is started by the IDE. It is working with Maven or Gradle at command line.

**Comment by martingrossmann** [comment]
Solved... thanks to @gogro

I used in IntelliJ the Gradle wrapper, but at command line the installed Gradle. Switching to 'real' Gradle in IntelliJ solved my issue. Maybe the different handling with Gradle cache causes my issue.
